mapping:
  "Corea del Sur": "South Korea"
  "Estados Unidos": "United States"
  "Reino Unido": "United Kingdom"
  "United Kingdom": "United Kingdom"
  "Canadá": "Canada"
  "México": "Mexico"
  "Bélgica": "Belgium"
  "Belgium": "Belgium"
  "Denmark": "Denmark"
  "Finland": "Finland"
  "Japón": "Japan"
  "Irán": "Iran"
  "Sudáfrica": "South Africa"
  "Arabia Saudita": "Saudi Arabia"
  "Costa Rica": "Costa Rica"
  "Venezuela": "Venezuela"
  "Colombia": "Colombia"
  "Argentina": "Argentina"
  "Chile": "Chile"
  "Guatemala": "Guatemala"
  "Panamá": "Panama"
  "Brasil": "Brazil"
  "Etiopía": "Ethiopia"
  "Túnez": "Tunisia"
  "Camerún": "Cameroon"
  "Costa de Marfil": "Ivory Coast"
  "Ruanda": "Rwanda"
  "Uganda": "Uganda"
  "Zambia": "Zambia"
  "Jordania": "Jordan"
  "Malasia": "Malaysia"
  "Uzbekistán": "Uzbekistan"
  "Liechtenstein": "Liechtenstein"
  "North Macedonia": "North Macedonia"
  "Slovakia": "Slovakia"
  "Hungary": "Hungary"
  "Latvia": "Latvia"
  "Romania": "Romania"
  "Kosovo": "Kosovo"
  "Albania": "Albania"
  "Portugal": "Portugal"
  "Austria": "Austria"
  "Estonia": "Estonia"
  "Belarus": "Belarus"
  "Lithuania": "Lithuania"
  "Vatican City": "Vatican City"
  "Montenegro": "Montenegro"
  "Indonesia": "Indonesia"
  "India": "India"
  "Singapur": "Singapore"
  "Cuba": "Cuba"
  "Malta": "Malta"
